version: '3'

vars:
  project_name: 'nikiv.dev'

tasks:
  default:
    desc: List available tasks.
    silent: true
    cmds:
      - task --list

  setup:
    desc: Install project dependencies with Bun.
    silent: true
    cmds:
      - |
        set -euo pipefail
        if ! command -v bun >/dev/null 2>&1; then
          echo "Bun runtime not found in PATH."
          echo "Install it via https://bun.sh/docs/installation"
          exit 1
        fi
        bun --version >/dev/null
        bun install --frozen-lockfile
        echo "Dependencies installed for ${PROJECT_NAME:-{{.project_name}}}."

  dev:
    desc: Start the Next.js dev server with Bun.
    silent: true
    cmds:
      - |
        set -euo pipefail
        if ! command -v bun >/dev/null 2>&1; then
          echo "Bun runtime not found in PATH."
          echo "Install it via https://bun.sh/docs/installation"
          exit 1
        fi
        if [ ! -d node_modules ]; then
          echo "node_modules missing; running 'bun install --frozen-lockfile'."
          bun install --frozen-lockfile
        fi
        bun run dev{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}
