version: '3'

vars:
  project_name: 'nikiv.dev'

tasks:
  default:
    desc: List available tasks.
    silent: true
    cmds:
      - task --list

  setup:
    desc: Install project dependencies with Bun.
    silent: true
    cmds:
      - |
        set -euo pipefail
        if ! command -v bun >/dev/null 2>&1; then
          echo "Bun runtime not found in PATH." >&2
          echo "Install it via https://bun.sh/docs/installation" >&2
          exit 1
        fi
        bun --version >/dev/null
        tmp_log="$(mktemp)"
        trap 'rm -f "$tmp_log"' EXIT
        if ! bun install --frozen-lockfile >"$tmp_log" 2>&1; then
          cat "$tmp_log" >&2
          exit 1
        fi
        rm -f "$tmp_log"
        trap - EXIT
        echo "✔️ you are setup"

  dev:
    desc: Start the Next.js dev server with Bun.
    silent: true
    cmds:
      - |
        set -euo pipefail
        if ! command -v bun >/dev/null 2>&1; then
          echo "Bun runtime not found in PATH."
          echo "Install it via https://bun.sh/docs/installation"
          exit 1
        fi
        if [ ! -d node_modules ]; then
          echo "node_modules missing; running 'bun install --frozen-lockfile'."
          bun install --frozen-lockfile
        fi
        bun run dev{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}
